drivers: fingerprint: ets: fix compilation error
Rename some functions to avoid duplicate symbol error by gcc:

aarch64-elf-ld.lld: error: duplicate symbol: FPS_init
>>> defined at ets_fps.c:102 (../drivers/input/fingerprint/ets_fps_mmi/ets_fps.c:102)
>>>            drivers/input/fingerprint/ets_fps_mmi/ets_fps.o:(FPS_init) in archive built-in.o
>>> defined at fpc1020_tee.c:38 (../drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.c:38)
>>>            drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.o:(.text+0x7C0) in archive built-in.o

aarch64-elf-ld.lld: error: duplicate symbol: FPS_register_notifier
>>> defined at ets_fps.c:117 (../drivers/input/fingerprint/ets_fps_mmi/ets_fps.c:117)
>>>            drivers/input/fingerprint/ets_fps_mmi/ets_fps.o:(FPS_register_notifier) in archive built-in.o
>>> defined at fpc1020_tee.c:50 (../drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.c:50)
>>>            drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.o:(.text+0x820) in archive built-in.o

aarch64-elf-ld.lld: error: duplicate symbol: FPS_unregister_notifier
>>> defined at ets_fps.c:141 (../drivers/input/fingerprint/ets_fps_mmi/ets_fps.c:141)
>>>            drivers/input/fingerprint/ets_fps_mmi/ets_fps.o:(FPS_unregister_notifier) in archive built-in.o
>>> defined at fpc1020_tee.c:74 (../drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.c:74)
>>>            drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.o:(.text+0x910) in archive built-in.o

aarch64-elf-ld.lld: error: duplicate symbol: FPS_notify
>>> defined at ets_fps.c:161 (../drivers/input/fingerprint/ets_fps_mmi/ets_fps.c:161)
>>>            drivers/input/fingerprint/ets_fps_mmi/ets_fps.o:(FPS_notify) in archive built-in.o
>>> defined at fpc1020_tee.c:94 (../drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.c:94)
>>>            drivers/input/fingerprint/fpc_fps_mmi/fpc1020_tee.o:(.text+0x98C) in archive built-in.o
make[2]: *** [../Makefile:1241: vmlinux] Error 1
make[1]: *** [/home/barryblackcat/fushiguro/Makefile:1225: vmlinux_prereq] Error 2
make[1]: Target '_all' not remade because of errors.